#!/bin/bash
source ../venv/bin/activate
python lightbulb_interace.py -id alfa &
python lightbulb_interace.py -id beta &
python lightbulb_interace.py -id gamma &
python lightbulb_interace.py -id delta &
python lightbulb_interace.py -id epsilon &
python lightbulb_interace.py -id zeta &
python lightbulb_interace.py -id kapa &
python lightbulb_interace.py -id lambda &
python lightbulb_interace.py -id pi &
python lightbulb_interace.py -id omega &
jobs